### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by austinmccalley** [eslachance/enmap-sqlite#2]
When I am installing enmap-sqlite on my Ubunut server I get the error which is attached.

Versions:
NPM v5.6.0
Node.js v9.9.0
Ubuntu 17.10 (Artful Aardvark)

[enmapsqlitefail.log](https://github.com/eslachance/enmap-sqlite/files/2174318/enmapsqlitefail.log)

**Comment by eslachance** [comment]
1- try to update npm by doing `npm i -g npm` , because 5.6.0 is older
2- as usual on linux, do `sudo apt update && sudo apt upgrade` to update any dependency and library in your framework. 
3- if that all still fails, in the log it tells you to "open a bug report". That's related to GCC, not enmap-sqlite. I unfortunately can't fix GCC ;)

**Comment by austinmccalley** [comment]
It was on a temporary server so I was able to re-install the OS on the
server and it fixed its self. Thank you for the help though.
